//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_OIDOCOCINA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RESERVAS
    {
        public int Id { get; set; }
        public int Id_Usuario { get; set; }
        public int Id_Mesa { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Dia { get; set; }
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public System.TimeSpan Hora { get; set; }
        [Display(Name = "Comensales")]
        public Nullable<int> Num_personas { get; set; }
        public virtual MESAS MESAS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
